# Generated by Django 4.2 on 2024-10-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
