# Generated by Django 5.0.1 on 2024-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', '대기 중'), ('Approved', '승인됨'), ('Rejected', '반려됨')], default='Pending', max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=13)),
            ],
        ),
    ]
