# Generated by Django 4.2 on 2024-10-23 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='submitted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
